export const START_WATCHING_CARD_DESIGNS_FOR_USER = 'WWC/START_WATCHING_CARD_DESIGNS_FOR_USER';
export const SET_MY_CARD_DESIGNS_LIST = 'WWC/SET_MY_CARD_DESIGNS_LIST';
export const SAVING_CARD_DESIGN = 'WWC/SAVING_CARD_DESIGN';
export const SAVE_CARD_DESIGN = 'WWC/SAVE_CARD_DESIGN';
