queue:
  name: Hosted Linux Preview
  demands: npm

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: ''
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'core'
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'core'
    verbose: 'false'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'react-app'
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'react-app'
    verbose: 'false'
    customCommand: 'test'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'react-app'
    verbose: 'false'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'functions'
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'functions'
    verbose: 'false'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: ''
    verbose: 'false'
    customCommand: 'test'

- task: Npm@1
  inputs:
    command: custom
    verbose: false
    customCommand: 'install firebase-tools -g'

- task: CmdLine@1
  inputs:
    filename: 'firebase'
    arguments: 'deploy --token $(FIREBASE_TOKEN)'