queue:
  name: Hosted Linux Preview
  demands: npm

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: ''
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'core'
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'core'
    verbose: 'false'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'react-app'
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'react-app'
    verbose: 'false'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'functions'
    verbose: 'false'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'functions'
    verbose: 'false'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: ''
    verbose: 'false'
    customCommand: 'test'

- task: CopyFiles@2
  inputs:
    Contents: |
     .firebaserc
     database.rules.json
     firebase.json
     firestore.indexes.json
     firestore.rules
     storage.rules
     functions/**
     react-app/build/**
    TargetFolder: '$(build.artifactstagingdirectory)/prezip/firebase-app/'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/prezip/firebase-app/'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/zip/firebase-app.zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/zip/firebase-app.zip'
    ArtifactName: 'firebase-app'
    publishLocation: Container