export const ADD_TEXT_SHAPE = 'WWC/ADD_TEXT_SHAPE';
export const SET_EDITING_SHAPE = 'WWC/SET_EDITING_SHAPE';
export const UPDATE_SHAPE_POSITION = 'WWC/UPDATE_PAGE_SHAPE_POSITION';
export const SAVE_CARD_DESIGN = 'WWC/SAVE_CARD_DESIGN';
export const SET_MY_CARD_DESIGNS_LIST = 'WWC/SET_MY_CARD_DESIGNS_LIST';
