export const DESIGNER_ADD_TEXT_SHAPE = 'WWC/DESIGNER_ADD_TEXT_SHAPE';
export const DESIGNER_UPDATE_SHAPE_WIDTH = 'WWC/DESIGNER_UPDATE_SHAPE_WIDTH';
export const DESIGNER_REMOVE_SHAPE = '/WWC/REMOVE_SHAPE';
export const DESIGNER_UPDATE_TEXT = 'WWC/DESIGNER_UPDATE_TEXT';
export const DESIGNER_SET_EDITING_SHAPE = 'WWC/DESIGNER_SET_EDITING_SHAPE';
export const DESIGNER_UPDATE_SHAPE_POSITION = 'WWC/DESIGNER_UPDATE_PAGE_SHAPE_POSITION';
export const DESIGNER_SAVING_CARD_DESIGN = 'WWC/DESIGNER_SAVING_CARD_DESIGN';
export const DESIGNER_SAVE_CARD_DESIGN = 'WWC/DESIGNER_SAVE_CARD_DESIGN';
export const DESIGNER_SET_MY_CARD_DESIGNS_LIST = 'WWC/DESIGNER_SET_MY_CARD_DESIGNS_LIST';
export const DESIGNER_SET_ACTIVE_CARD = 'WWC/DESIGNER_SET_ACTIVE_CARD';
export const DESIGNER_UNSET_ACTIVE_CARD = 'WWC/DESIGNER_UNSET_ACTIVE_CARD';
export const DESIGNER_START_WATCHING_CARD_DESIGNS_FOR_USER = 'WWC/DESIGNER_START_WATCHING_CARD_DESIGNS_FOR_USER';

export const DESIGNER_TOGGLE_ALLOW_USER_EDIT = 'WWC/DESIGNER_TOGGLE_ALLOW_USER_EDIT';
export type ToggleAllowUserEditArgs = { pageIndex: number; shapeIndex: number };
