export const ARTIST_DESIGNER_ADD_TEXT_SHAPE = 'WWC/ARTIST_DESIGNER_ADD_TEXT_SHAPE';
export const ARTIST_DESIGNER_UPDATE_SHAPE_WIDTH = 'WWC/ARTIST_DESIGNER_UPDATE_SHAPE_WIDTH';
export const ARTIST_DESIGNER_REMOVE_SHAPE = '/WWC/REMOVE_SHAPE';
export const ARTIST_DESIGNER_UPDATE_TEXT = 'WWC/ARTIST_DESIGNER_UPDATE_TEXT';
export const ARTIST_DESIGNER_SET_EDITING_SHAPE = 'WWC/ARTIST_DESIGNER_SET_EDITING_SHAPE';
export const ARTIST_DESIGNER_UPDATE_SHAPE_POSITION = 'WWC/ARTIST_DESIGNER_UPDATE_PAGE_SHAPE_POSITION';
export const ARTIST_DESIGNER_SAVING_CARD_DESIGN = 'WWC/ARTIST_DESIGNER_SAVING_CARD_DESIGN';
export const ARTIST_DESIGNER_SAVE_CARD_DESIGN = 'WWC/ARTIST_DESIGNER_SAVE_CARD_DESIGN';
export const ARTIST_DESIGNER_SET_MY_CARD_DESIGNS_LIST = 'WWC/ARTIST_DESIGNER_SET_MY_CARD_DESIGNS_LIST';
export const ARTIST_DESIGNER_SET_ACTIVE_CARD = 'WWC/ARTIST_DESIGNER_SET_ACTIVE_CARD';
export const ARTIST_DESIGNER_UNSET_ACTIVE_CARD = 'WWC/ARTIST_DESIGNER_UNSET_ACTIVE_CARD';
export const ARTIST_DESIGNER_START_WATCHING_CARD_DESIGNS_FOR_USER =
  'WWC/ARTIST_DESIGNER_START_WATCHING_CARD_DESIGNS_FOR_USER';

export const ARTIST_DESIGNER_TOGGLE_ALLOW_USER_EDIT = 'WWC/ARTIST_DESIGNER_TOGGLE_ALLOW_USER_EDIT';
export type ToggleAllowUserEditArgs = { pageIndex: number; shapeIndex: number };
