export const CUSTOMER_ADD_CARD_TO_BASKET = 'WWC/ADD_TO_BASKET';
export const START_WATCHING_ALL_CARD_DESIGNS = 'WWC/START_WATCHING_ALL_CARD_DESIGNS';
export const SET_CARDS_LIST = 'WWC/SET_CARDS_LIST';
