export const CUSTOMER_DESIGNER_ADD_TEXT_SHAPE = 'WWC/CUSTOMER_DESIGNER_ADD_TEXT_SHAPE';
export const CUSTOMER_DESIGNER_UPDATE_SHAPE_WIDTH = 'WWC/CUSTOMER_DESIGNER_UPDATE_SHAPE_WIDTH';
export const CUSTOMER_DESIGNER_REMOVE_SHAPE = '/WWC/REMOVE_SHAPE';
export const CUSTOMER_DESIGNER_UPDATE_TEXT = 'WWC/CUSTOMER_DESIGNER_UPDATE_TEXT';
export const CUSTOMER_DESIGNER_SET_EDITING_SHAPE = 'WWC/CUSTOMER_DESIGNER_SET_EDITING_SHAPE';
export const CUSTOMER_DESIGNER_UPDATE_SHAPE_POSITION = 'WWC/CUSTOMER_DESIGNER_UPDATE_PAGE_SHAPE_POSITION';
export const CUSTOMER_DESIGNER_SET_ACTIVE_CARD = 'WWC/CUSTOMER_DESIGNER_SET_ACTIVE_CARD';
export const CUSTOMER_DESIGNER_UNSET_ACTIVE_CARD = 'WWC/CUSTOMER_DESIGNER_UNSET_ACTIVE_CARD';
